AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - Amazon API Gateway to AWS Lambda to Amazon DynamoDB (uksb-1tthgi812) (tag:apigw-lambda-dynamodb)
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WeatherData
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      Tags:
        - Key: Name
          Value: WeatherData
  ApiGatewayApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: WeatherAPI
      Description: Weather API
      FailOnWarnings: true
      EndpointConfiguration:
        Types:
          - REGIONAL
      CorsConfiguration:
        AllowMethods: "'OPTIONS,GET,POST,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigins: "'*'"
  LambdaFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function inserts data into DynamoDB table'
    Properties:
      FunctionName: WeatherFunction
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: s3://cf-templates-1408v8pnvdywj-ap-south-1/cygnum/lambda_function.zip
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
  
  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete_function.lambda_handler
      Runtime: python3.8
      CodeUri: s3://cf-templates-1408v8pnvdywj-ap-south-1/cygnum/delete_function.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            Path: /delete
            Method: delete
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: authorizer.lambda_handler
      Runtime: python3.8
      CodeUri: s3://cf-templates-1408v8pnvdywj-ap-south-1/cygnum/authorizer.zip
      Events:
        AuthorizerEvent:
          Type: Api
          Properties:
            Path: /auth
            Method: get
  
Outputs:
  EndpointUrl:
    Description: 'HTTP REST endpoint URL'
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
